---
.travis.yml:
  includes:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  extras:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
